// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyHangHoaAPI.Data;

#nullable disable

namespace QuanLyHangHoaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526132842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("QuanLyHangHoaAPI.Models.HangHoa", b =>
                {
                    b.Property<string>("MaHang")
                        .HasColumnType("TEXT");

                    b.Property<double>("DonGia")
                        .HasColumnType("REAL");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaHang");

                    b.ToTable("HangHoas");
                });
#pragma warning restore 612, 618
        }
    }
}
